version: "3"
services:
  serving:
    image: tensorflow/serving
    restart: always
    volumes:
      - ./model:/models/test_model
    environment:
      - MODEL_NAME=test_model
    ports:
      - "8501:8501"